// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrU-ItYjUSTQsFou89HCNLMJlsf90ke2A',
    appId: '1:1067341700350:web:f988d13b31b0507bb359af',
    messagingSenderId: '1067341700350',
    projectId: 'dam-project-e2a33',
    authDomain: 'dam-project-e2a33.firebaseapp.com',
    databaseURL: 'https://dam-project-e2a33-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dam-project-e2a33.appspot.com',
    measurementId: 'G-YCPYYWBYE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgKgshl3jqf9ViOmH6PIvKHdViPnB2H_w',
    appId: '1:1067341700350:android:e257312d5377a2d8b359af',
    messagingSenderId: '1067341700350',
    projectId: 'dam-project-e2a33',
    databaseURL: 'https://dam-project-e2a33-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dam-project-e2a33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkU1tjCegSqjmSoqMTAm4Hr_cHzWr5RyY',
    appId: '1:1067341700350:ios:8e90ed9297cd7bd5b359af',
    messagingSenderId: '1067341700350',
    projectId: 'dam-project-e2a33',
    databaseURL: 'https://dam-project-e2a33-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dam-project-e2a33.appspot.com',
    iosBundleId: 'com.dashboard.flutter.app.flutterDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkU1tjCegSqjmSoqMTAm4Hr_cHzWr5RyY',
    appId: '1:1067341700350:ios:8e90ed9297cd7bd5b359af',
    messagingSenderId: '1067341700350',
    projectId: 'dam-project-e2a33',
    databaseURL: 'https://dam-project-e2a33-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dam-project-e2a33.appspot.com',
    iosBundleId: 'com.dashboard.flutter.app.flutterDashboard',
  );
}
